//
//  LKInteractor.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit
import Alamofire

class LKPresenterToInteractor: LKPresenterToInteractorProtocol {

    var presenter: LKInteractorToPresenterProtocol?
    func fetchData() {
            //do something with alamofire
    }
}
