//
//  LKPresenter.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

class LKViewToPresenter: LKViewToPresenterProtocol {

    var view: LKPresenterToViewProtocol?
    var interactor: LKPresenterToInteractorProtocol?
    var router: LKPresenterToRouterProcotol?
    
    func updateView() {
        interactor?.fetchData()
    }

}

extension LKViewToPresenter: LKInteractorToPresenterProtocol{
    func dataFetched() {
        view?.showData()
    }
    
    func dataFetchedFailed(errorName: String ,statusCode: Int) {
        view?.showError(errorName: errorName, statusCode: statusCode)
    }
    
    func viewLoading() {
        view?.hideHud()
    }
}
