//
//  LKProtocols.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

//MARK: Presenter - Router
protocol LKPresenterToRouterProcotol: class {
    static func createModule() -> UIViewController
}

//MARK: View - Presenter
protocol LKViewToPresenterProtocol: class {
    var view: LKPresenterToViewProtocol? {get set}
    var interactor: LKPresenterToInteractorProtocol? {get set}
    var router: LKPresenterToRouterProcotol? {get set}
    
    func updateView()
}

//MARK: Presenter - View
protocol LKPresenterToViewProtocol {
    func showData()
    func showError(errorName: String, statusCode: Int)
    func hideHud()
}

//MARK: Presenter - Interactor
protocol LKPresenterToInteractorProtocol {
    var presenter: LKInteractorToPresenterProtocol? {get set}
    func fetchData()
}

//MARK: Interactor - Presenter
protocol LKInteractorToPresenterProtocol: class {
    func dataFetched()
    func dataFetchedFailed(errorName: String ,statusCode: Int)
    func viewLoading()
}

