//
//  LKRouter.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit

class LKPresenterToRouter: BaseClass, LKPresenterToRouterProcotol {
    
    static func createModule() -> UIViewController {
        let view = mainStoryBoard.instantiateViewController(withIdentifier: "LKViewController") as! LKViewController
        var interactor: LKPresenterToInteractorProtocol = LKPresenterToInteractor()
        let presenter: LKViewToPresenterProtocol & LKInteractorToPresenterProtocol = LKViewToPresenter()
        let router: LKPresenterToRouterProcotol = LKPresenterToRouter()
        
        presenter.view = view
        presenter.router = router
        presenter.interactor = interactor
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
}
