//
//  LKViewController.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit
import PKHUD

class LKViewController: BaseClass {

    var presenter: LKViewToPresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension LKViewController: LKPresenterToViewProtocol {
    func showData() {
        //do something & add parameter data
    }
    
    func showError(errorName: String, statusCode: Int) {
        showAlert(errorName: errorName, statusCode: statusCode)
    }
    
    func hideHud() {
        HUD.hide()
    }
}
