//
//  BBViewController.swift
//  ExampleVipew
//
//  Created yana mulyana on 22/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit

class BBViewController: UIViewController {

//    var presenter: BBViewToPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension BBViewController: BBPresenterToViewProtocol {
    
}
