//
//  OOProtocols.swift
//  ExampleVipew
//
//  Created yana mulyana on 22/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

//MARK: View - Presenter
protocol OOPresenterToRouterProcotol: class {
    static func createModule() -> UIViewController
}


protocol OOViewToPresenterProtocol: class {
    var view: OOPresenterToViewProtocol? {get set}
    var interactor: OOPresenterToInteractorProtocol? {get set}
    var router: OOPresenterToRouterProcotol? {get set}
    
    func updateView()
}

protocol OOPresenterToViewProtocol {
    func showData()
    func showError(errorName: String, statusCode: Int)
    func hideHud()
}

protocol OOPresenterToInteractorProtocol {
    var presenter: OOInteractorToPresenterProtocol? {get set}
    func fetchData()
}

protocol OOInteractorToPresenterProtocol: class {
    func dataFetched()
    func dataFetchedFailed(errorName: String ,statusCode: Int)
    func viewLoading()
}

