//
//  OOViewController.swift
//  ExampleVipew
//
//  Created yana mulyana on 22/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit
import PKHUD

class OOViewController: BaseClass {

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension OOViewController: OOPresenterToViewProtocol {
    func showData() {
        
    }
    
    func showError(errorName: String, statusCode: Int) {
        showAlert(errorName: errorName, statusCode: statusCode)
    }
    
    func hideHud() {
        HUD.hide()
    }
}
