//
//  ZZProtocols.swift
//  ExampleVipew
//
//  Created yana mulyana on 22/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation

////MARK: Presenter - Router
//protocol ZZPresenterToRouterProcotol: class {
//    static func createModule() -> UIViewController
//}
//MARK: View - Presenter
protocol ZZViewToPresenterProtocol: class {
//    var view: identifier___PresenterToViewProtocol? {get set}
//    var interactor: identifier___PresenterToInteractorProtocol? {get set}
//    var router: identifier___PresenterToRouterProcotol? {get set}

    func updateView()
}

//MARK: Presenter - View
protocol ___VARIABLE_productName:identifier___PresenterToViewProtocol: class {
    func showData()
    func showError(errorName: String, statusCode: Int)
    func hideHud()
}

//MARK: Presenter - Interactor
protocol ___VARIABLE_productName:identifier___PresenterToInteractorProtocol: class {
//    var presenter: identifier___InteractorToPresenterProtocol? {get set}
    func fetchData()
}

////MARK: Interactor - Presenter
//protocol ZZInteractorToPresenterProtocol: class {
//    func fetchedData()
//    func fetchedDataFailed(errorName: String ,statusCode: Int)
//    func viewLoading()
//}
