//
//  ZZViewController.swift
//  ExampleVipew
//
//  Created yana mulyana on 22/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit

class ZZViewController: UIViewController {

//    var presenter: ZZViewToPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension ZZViewController: ZZPresenterToViewProtocol {
    
}
