//
//  ProfileRouter.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit

class ProfilePresenterToRouter: BaseClass, ProfilePresenterToRouterProcotol {
    
    static func createModule() -> UIViewController {
        let view = mainStoryBoard(storyName: "Other").instantiateViewController(withIdentifier: "ProfileViewController") as! ProfileViewController
        var interactor: ProfilePresenterToInteractorProtocol = ProfilePresenterToInteractor()
        let presenter: ProfileViewToPresenterProtocol & ProfileInteractorToPresenterProtocol = ProfileViewToPresenter()
        let router: ProfilePresenterToRouterProcotol = ProfilePresenterToRouter()
        
        presenter.view = view
        presenter.router = router
        presenter.interactor = interactor
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
    
}
