//
//  ProfileInteractor.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit
import Alamofire

class ProfilePresenterToInteractor: DebugError, ProfilePresenterToInteractorProtocol {

    var presenter: ProfileInteractorToPresenterProtocol?
    func fetchData() {
        Alamofire.request(Constants.URL).responseJSON { response in
            switch response.result {
            case .success:
                do {
                    let commentResult = try JSONDecoder().decode(ContactResult.self, from: response.data!)
                    self.presenter?.dataFetched(news: commentResult)
                } catch let err {
                    print(err)
                }
            case .failure(let error):
                self.debug(error: error, statusCode: response.response?.statusCode as Any)
                self.presenter?.dataFetchedFailed(errorName: error.localizedDescription, statusCode: response.response?.statusCode ?? 0)
            }
            self.presenter?.viewLoading()
        }
    }
}
