//
//  ProfileProtocols.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

//MARK: Presenter - Router
protocol ProfilePresenterToRouterProcotol: class {
    static func createModule() -> UIViewController
}

//MARK: View - Presenter
protocol ProfileViewToPresenterProtocol: class {
    var view: ProfilePresenterToViewProtocol? {get set}
    var interactor: ProfilePresenterToInteractorProtocol? {get set}
    var router: ProfilePresenterToRouterProcotol? {get set}
    
    func updateView()
}

//MARK: Presenter - View
protocol ProfilePresenterToViewProtocol {
    func showData(news: ContactResult)
    func showError(errorName: String, statusCode: Int)
    func hideHud()
}

//MARK: Presenter - Interactor
protocol ProfilePresenterToInteractorProtocol {
    var presenter: ProfileInteractorToPresenterProtocol? {get set}
    func fetchData()
}

//MARK: Interactor - Presenter
protocol ProfileInteractorToPresenterProtocol: class {
    func dataFetched(news: ContactResult)
    func dataFetchedFailed(errorName: String ,statusCode: Int)
    func viewLoading()
}

