//
//  ProfileViewController.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit
import PKHUD

class ProfileViewController: BaseClass {

    var presenter: ProfileViewToPresenterProtocol?
    @IBOutlet weak var lblName: UILabel!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.updateView()
    }

}

extension ProfileViewController: ProfilePresenterToViewProtocol {
    func showData(news: ContactResult) {
        lblName.text = news.contact[0].name
    }
    
    func showError(errorName: String, statusCode: Int) {
        showAlert(errorName: errorName, statusCode: statusCode)
    }
    
    func hideHud() {
        HUD.hide()
    }
}
