//
//  ProfilePresenter.swift
//  ExampleVipew
//
//  Created yana mulyana on 23/07/18.
//  Copyright © 2018 yana mulyana. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

class ProfileViewToPresenter: ProfileViewToPresenterProtocol {
    
    var view: ProfilePresenterToViewProtocol?
    var interactor: ProfilePresenterToInteractorProtocol?
    var router: ProfilePresenterToRouterProcotol?
    
    func updateView() {
        interactor?.fetchData()
    }

}

extension ProfileViewToPresenter: ProfileInteractorToPresenterProtocol{
    func dataFetched(news: ContactResult) {
        view?.showData(news: news)
    }
    
    func dataFetchedFailed(errorName: String ,statusCode: Int) {
        view?.showError(errorName: errorName, statusCode: statusCode)
    }
    
    func viewLoading() {
        view?.hideHud()
    }
}
